name: tdd_demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc:
  dartz: ^0.10.0
  equatable:
  entity:
  dio: ^4.0.1
  flutter_bloc: ^7.3.3
  get_it: ^7.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
